"""
Tasks Categories module initialization.
2-level architecture similar to Architecture_Categories.
"""

from .Semantic import SEMANTIC_TASKS, LINGUISTICS_AND_LANGUAGE, PROGRAMMING_AND_CODE, MATHEMATICS_SYMBOLIC, LOGIC_AND_KNOWLEDGE, CYBERSECURITY, PHILOSOPHY_AND_HUMANITIES, LAW_AND_JURISPRUDENCE
from .Perceptual import PERCEPTUAL_TASKS, COMPUTER_VISION, MEDICAL_IMAGING, AUDIO_AND_SOUND, TACTILE_AND_PHYSICAL_SENSORS, MULTISENSORY
from .Structured import STRUCTURED_TASKS, TABULAR_DATA, TIME_SERIES, GRAPHS, BIOLOGY, MEDICAL_DATA, HIERARCHIES_AND_ONTOLOGIES
from .Physical import PHYSICAL_TASKS, PHYSICS, QUANTUM_MECHANICS, ASTROPHYSICS_AND_ASTRONOMY, CHEMISTRY, EARTH_SCIENCES, MATERIALS_SCIENCE, ECOLOGY_AND_ENVIRONMENT
from .Control import CONTROL_TASKS, ROBOTICS, CONTROL_THEORY, OPTIMIZATION, DECISION_MAKING, AUTONOMOUS_SYSTEMS, LOGISTICS_AND_SUPPLY_CHAIN, ENERGY_AND_INFRASTRUCTURE
from .Hybrid import HYBRID_TASKS, MULTIMODAL, MULTIDIMENSIONAL_PROJECTIONS, CROSS_DOMAIN, MEDICINE_AND_TECHNOLOGY, META_TASKS, COMBINATORIAL_TASKS

__all__ = [
    # Main categories
    "SEMANTIC_TASKS",
    "PERCEPTUAL_TASKS",
    "STRUCTURED_TASKS",
    "PHYSICAL_TASKS",
    "CONTROL_TASKS",
    "HYBRID_TASKS",
    
    # SEMANTIC subcategories
    "LINGUISTICS_AND_LANGUAGE",
    "PROGRAMMING_AND_CODE",
    "MATHEMATICS_SYMBOLIC",
    "LOGIC_AND_KNOWLEDGE",
    "CYBERSECURITY",
    "PHILOSOPHY_AND_HUMANITIES",
    "LAW_AND_JURISPRUDENCE",
    
    # PERCEPTUAL subcategories
    "COMPUTER_VISION",
    "MEDICAL_IMAGING",
    "AUDIO_AND_SOUND",
    "TACTILE_AND_PHYSICAL_SENSORS",
    "MULTISENSORY",
    
    # STRUCTURED subcategories
    "TABULAR_DATA",
    "TIME_SERIES",
    "GRAPHS",
    "BIOLOGY",
    "MEDICAL_DATA",
    "HIERARCHIES_AND_ONTOLOGIES",
    
    # PHYSICAL subcategories
    "PHYSICS",
    "QUANTUM_MECHANICS",
    "ASTROPHYSICS_AND_ASTRONOMY",
    "CHEMISTRY",
    "EARTH_SCIENCES",
    "MATERIALS_SCIENCE",
    "ECOLOGY_AND_ENVIRONMENT",
    
    # CONTROL subcategories
    "ROBOTICS",
    "CONTROL_THEORY",
    "OPTIMIZATION",
    "DECISION_MAKING",
    "AUTONOMOUS_SYSTEMS",
    "LOGISTICS_AND_SUPPLY_CHAIN",
    "ENERGY_AND_INFRASTRUCTURE",
    
    # HYBRID subcategories
    "MULTIMODAL",
    "MULTIDIMENSIONAL_PROJECTIONS",
    "CROSS_DOMAIN",
    "MEDICINE_AND_TECHNOLOGY",
    "META_TASKS",
    "COMBINATORIAL_TASKS"
]
